### ISSUE TITLE
Remove WCP assemblies

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/WindowsPowerShellCompatibilityPack#17]
After some internal discussion, we decided that:

1. we would ship the WCP shims as a separate module to support Windows PowerShell
2. we would ship the WCP implemented assemblies with PSCore6.1

This means we should remove the WCP shims and implemented assemblies from this module and we can also make it only compatible with `Core`

**Comment by markekraus** [comment]
@SteveL-MSFT I don't have the exact numbers but including the WCP in PSCore6.1 will increase the size ~10MB. PowerShell is already pretty large. I'm not opposed to them being included, but, it is a size increase that will make pwsh a tougher sell for embeded/IoT. I am assuming this was considered, but I wanted to bring attention to it in case it was not.

**Comment by SteveL-MSFT** [comment]
@markekraus currently, the delta of WCP assemblies we don't already include is only ~3.5MB.  The total install size on my Win10 box is ~140MB.

Since some WCP assemblies actually work on non-Windows, current thinking is to include those on the non-Windows packages of PSCore6 as well.  For size constraint systems, we have a longer term effort for minimal PSCore6 (maybe 6.2?)

**Comment by markekraus** [comment]
Awesome! I thought it was much larger.
Also, glad to hear the the minimal idea is not dead.
