### ISSUE TITLE
Aliases are too long

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/WindowsPowerShellCompatibilityPack#2]
Feedback from PR of initial code drop is that the aliases should be reworked:

```powershell
AliasesToExport = @(
    'awinfn',
    'cpwinmo',
    'cwinmo',
    'gwinmo',
    'iwincm',
    'ipwinmo',
    'inwinsn'
)
```

Perhaps consider not having aliases for this module?

**Comment by markekraus** [comment]
+1 for no aliases. If they could be a bit shorter, maybe.

**Comment by iSazonov** [comment]
We can have dozens and hundreds of installed modules - if each one will add a "short" aliases then there will be lots of conflicts. No one remembers these aliasess if not used every day for a long time. Users themselves should create aliases when it is important to them.

**Comment by BrucePay** [comment]
Agreed. I'll remove the aliases.
